#!/usr/bin/env python3
"""
compare_rl_baselines.py

Combine PPO, A2C, and CQL outputs into clean comparison tables and figures.

This script reads:
    1. PPO/A2C evaluation metrics from evaluate_ppo_a2c_agents.py
    2. PPO/A2C OPE metrics from evaluate_ope_ppo_a2c.py
    3. CQL evaluation metrics from evaluate_cql_agent.py

It creates:
    - combined_rl_baseline_summary.csv
    - combined_ppo_a2c_ope_metrics.csv
    - rl_baseline_reward_comparison.png
    - rl_baseline_vasopressor_comparison.png
    - ope_comparison_ppo_a2c.png
    - is_instability_ppo_a2c.png

Important:
    PPO/A2C rollout rewards and CQL learned Q-value diagnostics are not identical
    evaluation quantities. Therefore, the script keeps CQL value diagnostics
    separate from PPO/A2C rollout rewards while still allowing treatment-policy
    behavior comparison through fluid and vasopressor intensity.
"""

import os
import re
import glob
import json
from pathlib import Path
from typing import Optional, Dict, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

RESULTS_DIR = "../results"
FIGURES_DIR = "../figures"

# CQL evaluation outputs may be stored outside ../results depending on how
# evaluate_cql_agent.py was run. These patterns make the script flexible.
CQL_EVAL_PATTERNS = [
    "../cql_evaluation_results*/cql_evaluation_metrics.json",
    "cql_evaluation_results*/cql_evaluation_metrics.json",
    "../results/cql_evaluation_results*/cql_evaluation_metrics.json",
    "../results/**/cql_evaluation_metrics.json",
]

SEEDS = [1, 2, 3, 4, 5]

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR, exist_ok=True)


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------

def latest_file(pattern: str) -> Optional[str]:
    files = glob.glob(pattern)
    if not files:
        return None
    return max(files, key=os.path.getmtime)


def read_latest_csv(pattern: str, label: str) -> Optional[pd.DataFrame]:
    path = latest_file(pattern)
    if path is None:
        print(f"[WARN] No file found for {label}: {pattern}")
        return None
    print(f"[INFO] Loading {label}: {path}")
    return pd.read_csv(path)


def extract_seed_from_path(path: str) -> Optional[int]:
    match = re.search(r"seed[_-]?(\d+)", path, flags=re.IGNORECASE)
    if match:
        return int(match.group(1))
    return None


def safe_float(value, default=np.nan) -> float:
    try:
        if value is None:
            return float(default)
        return float(value)
    except Exception:
        return float(default)


def save_dataframe(df: pd.DataFrame, path: str, label: str) -> None:
    df.to_csv(path, index=False)
    print(f"[INFO] Saved {label}: {path}")


# ---------------------------------------------------------------------
# Load PPO/A2C evaluation metrics
# ---------------------------------------------------------------------

def load_ppo_a2c_eval_metrics() -> pd.DataFrame:
    """
    Load deterministic rollout evaluation metrics generated by
    evaluate_ppo_a2c_agents.py.
    """
    df = read_latest_csv(
        pattern=f"{RESULTS_DIR}/ppo_a2c_evaluation_metrics_*.csv",
        label="PPO/A2C evaluation metrics",
    )

    if df is None:
        return pd.DataFrame()

    df = df[df["seed"].isin(SEEDS)].copy()

    required_cols = [
        "algorithm",
        "seed",
        "mean_reward",
        "std_reward",
        "min_reward",
        "max_reward",
        "mean_episode_length",
        "std_episode_length",
        "mean_fluid_bin",
        "mean_vasopressor_bin",
        "action_match_rate",
    ]

    for col in required_cols:
        if col not in df.columns:
            df[col] = np.nan

    df["policy_type"] = "online_actor_critic_rollout"
    df["return_metric_type"] = "deterministic_policy_rollout_reward"
    df["cql_dm_initial_value"] = np.nan
    df["observed_dataset_episode_return_mean"] = np.nan

    return df


# ---------------------------------------------------------------------
# Load PPO/A2C OPE metrics
# ---------------------------------------------------------------------

def load_ppo_a2c_ope_metrics() -> pd.DataFrame:
    """
    Load OPE diagnostics generated by evaluate_ope_ppo_a2c.py.

    Falls back to old PPO-only files if the combined PPO/A2C file is not found.
    """
    combined = read_latest_csv(
        pattern=f"{RESULTS_DIR}/ppo_a2c_ope_metrics_*.csv",
        label="PPO/A2C OPE metrics",
    )

    if combined is not None:
        df = combined.copy()
        if "seed" in df.columns:
            df = df[df["seed"].isin(SEEDS)].copy()
        return df

    print("[WARN] Combined PPO/A2C OPE file not found. Trying old PPO-only OPE files...")

    old_files = glob.glob(f"{RESULTS_DIR}/ppo_temporal_25_seed_*_ope_metrics_*.csv")
    dfs = []

    for file in old_files:
        temp = pd.read_csv(file)
        if "seed" in temp.columns and int(temp["seed"].iloc[0]) in SEEDS:
            if "algorithm" not in temp.columns:
                temp["algorithm"] = "PPO"
            dfs.append(temp)

    if not dfs:
        return pd.DataFrame()

    return pd.concat(dfs, ignore_index=True)


# ---------------------------------------------------------------------
# Load CQL evaluation metrics
# ---------------------------------------------------------------------

def load_cql_eval_metrics() -> pd.DataFrame:
    """
    Load CQL evaluation JSON files generated by evaluate_cql_agent.py.

    The CQL evaluator may be run once or once per seed. This loader supports both.
    """
    files: List[str] = []

    for pattern in CQL_EVAL_PATTERNS:
        files.extend(glob.glob(pattern, recursive=True))

    files = sorted(set(files))

    if not files:
        print("[WARN] No CQL evaluation metrics JSON files found.")
        return pd.DataFrame()

    rows = []

    for file in files:
        with open(file, "r", encoding="utf-8") as f:
            metrics: Dict = json.load(f)

        seed = metrics.get("seed", None)

        if seed is None:
            # Try checkpoint/config seed if available
            model_path = str(metrics.get("model_path", ""))
            seed = extract_seed_from_path(model_path)

        if seed is None:
            seed = extract_seed_from_path(file)

        row = {
            "algorithm": "CQL",
            "seed": seed if seed is not None else -1,
            "policy_type": "offline_cql_greedy_policy",
            "return_metric_type": "learned_q_value_diagnostic_not_rollout_reward",
            "mean_reward": np.nan,
            "std_reward": np.nan,
            "min_reward": np.nan,
            "max_reward": np.nan,
            "mean_episode_length": np.nan,
            "std_episode_length": np.nan,
            "mean_fluid_bin": safe_float(metrics.get("cql_greedy_mean_fluid_bin")),
            "mean_vasopressor_bin": safe_float(metrics.get("cql_greedy_mean_vaso_bin")),
            "action_match_rate": safe_float(metrics.get("cql_dataset_action_match_rate")),
            "cql_dm_initial_value": safe_float(
                metrics.get("dm_estimated_initial_state_value_mean")
            ),
            "observed_dataset_episode_return_mean": safe_float(
                metrics.get("observed_dataset_episode_return_mean",
                            metrics.get("observed_episode_return_mean"))
            ),
            "dataset_reward_mean": safe_float(metrics.get("dataset_reward_mean")),
            "dataset_reward_std": safe_float(metrics.get("dataset_reward_std")),
            "q_max_mean": safe_float(metrics.get("q_max_mean")),
            "q_max_std": safe_float(metrics.get("q_max_std")),
            "bellman_mse": safe_float(metrics.get("bellman_mse")),
            "source_file": file,
        }

        rows.append(row)

    df = pd.DataFrame(rows)

    # Keep seeds 3,4,5 when available. If CQL was only run once and seed cannot
    # be inferred, keep that row.
    if "seed" in df.columns:
        known_seed_df = df[df["seed"].isin(SEEDS)].copy()
        unknown_seed_df = df[df["seed"] == -1].copy()

        if not known_seed_df.empty:
            df = known_seed_df
        elif not unknown_seed_df.empty:
            df = unknown_seed_df

    print(f"[INFO] Loaded {len(df)} CQL evaluation row(s).")
    return df


# ---------------------------------------------------------------------
# Build combined baseline table
# ---------------------------------------------------------------------

def build_combined_baseline_table(
    eval_df: pd.DataFrame,
    cql_df: pd.DataFrame,
) -> pd.DataFrame:
    common_cols = [
        "algorithm",
        "seed",
        "policy_type",
        "return_metric_type",
        "mean_reward",
        "std_reward",
        "min_reward",
        "max_reward",
        "mean_episode_length",
        "std_episode_length",
        "mean_fluid_bin",
        "mean_vasopressor_bin",
        "action_match_rate",
        "cql_dm_initial_value",
        "observed_dataset_episode_return_mean",
    ]

    frames = []

    if not eval_df.empty:
        for col in common_cols:
            if col not in eval_df.columns:
                eval_df[col] = np.nan
        frames.append(eval_df[common_cols].copy())

    if not cql_df.empty:
        for col in common_cols:
            if col not in cql_df.columns:
                cql_df[col] = np.nan
        frames.append(cql_df[common_cols].copy())

    if not frames:
        return pd.DataFrame(columns=common_cols)

    combined = pd.concat(frames, ignore_index=True)

    algorithm_order = {"PPO": 0, "A2C": 1, "CQL": 2}
    combined["algorithm_order"] = combined["algorithm"].map(algorithm_order).fillna(99)
    combined = combined.sort_values(["algorithm_order", "seed"]).drop(columns=["algorithm_order"])

    return combined


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------

def plot_ppo_a2c_reward(eval_df: pd.DataFrame) -> None:
    if eval_df.empty or "mean_reward" not in eval_df.columns:
        return

    plot_df = eval_df[eval_df["algorithm"].isin(["PPO", "A2C"])].copy()
    if plot_df.empty:
        return

    plt.figure(figsize=(8, 5))

    for algorithm, group in plot_df.groupby("algorithm"):
        group = group.sort_values("seed")
        plt.plot(
            group["seed"].astype(str),
            group["mean_reward"],
            marker="o",
            label=algorithm,
        )

    plt.xlabel("Seed")
    plt.ylabel("Mean episode reward")
    plt.title("PPO vs A2C Deterministic Policy Evaluation")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.legend()
    plt.tight_layout()

    path = f"{FIGURES_DIR}/rl_baseline_reward_comparison.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"[INFO] Saved reward comparison figure: {path}")


def plot_vasopressor_comparison(combined_df: pd.DataFrame) -> None:
    if combined_df.empty or "mean_vasopressor_bin" not in combined_df.columns:
        return

    plot_df = combined_df.copy()
    plot_df = plot_df[np.isfinite(plot_df["mean_vasopressor_bin"])]

    if plot_df.empty:
        return

    labels = [
        f"{row.algorithm}\nSeed {int(row.seed) if row.seed != -1 else 'NA'}"
        for row in plot_df.itertuples()
    ]

    plt.figure(figsize=(10, 5))
    plt.bar(labels, plot_df["mean_vasopressor_bin"])
    plt.xlabel("Algorithm / seed")
    plt.ylabel("Mean selected vasopressor bin")
    plt.title("Vasopressor Intensity Across PPO, A2C, and CQL")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()

    path = f"{FIGURES_DIR}/rl_baseline_vasopressor_comparison.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"[INFO] Saved vasopressor comparison figure: {path}")


def plot_fluid_comparison(combined_df: pd.DataFrame) -> None:
    if combined_df.empty or "mean_fluid_bin" not in combined_df.columns:
        return

    plot_df = combined_df.copy()
    plot_df = plot_df[np.isfinite(plot_df["mean_fluid_bin"])]

    if plot_df.empty:
        return

    labels = [
        f"{row.algorithm}\nSeed {int(row.seed) if row.seed != -1 else 'NA'}"
        for row in plot_df.itertuples()
    ]

    plt.figure(figsize=(10, 5))
    plt.bar(labels, plot_df["mean_fluid_bin"])
    plt.xlabel("Algorithm / seed")
    plt.ylabel("Mean selected fluid bin")
    plt.title("Fluid Intensity Across PPO, A2C, and CQL")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()

    path = f"{FIGURES_DIR}/rl_baseline_fluid_comparison.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"[INFO] Saved fluid comparison figure: {path}")


def normalize_ope_columns(ope_df: pd.DataFrame) -> pd.DataFrame:
    """
    Support both old and new OPE column names.
    """
    df = ope_df.copy()

    rename_map = {
        "true_return": "true_average_return_from_policy_rollout",
        "dm_estimate": "dm_proxy_estimate",
    }

    for old, new in rename_map.items():
        if old in df.columns and new not in df.columns:
            df[new] = df[old]

    if "algorithm" not in df.columns:
        df["algorithm"] = "PPO"

    return df


def plot_ope_comparison(ope_df: pd.DataFrame) -> None:
    if ope_df.empty:
        return

    df = normalize_ope_columns(ope_df)

    needed = [
        "algorithm",
        "seed",
        "true_average_return_from_policy_rollout",
        "wis_estimate",
        "dm_proxy_estimate",
    ]

    for col in needed:
        if col not in df.columns:
            print(f"[WARN] OPE plot skipped because column is missing: {col}")
            return

    plot_df = df[needed].copy()
    plot_df["algorithm_seed"] = plot_df["algorithm"].astype(str) + "_seed_" + plot_df["seed"].astype(str)
    plot_df = plot_df.set_index("algorithm_seed")

    ax = plot_df[
        [
            "true_average_return_from_policy_rollout",
            "wis_estimate",
            "dm_proxy_estimate",
        ]
    ].plot(kind="bar", figsize=(11, 5))

    ax.set_xlabel("Algorithm / seed")
    ax.set_ylabel("Estimated return")
    ax.set_title("OPE Comparison Across PPO and A2C Seeds")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()

    path = f"{FIGURES_DIR}/ope_comparison_ppo_a2c.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"[INFO] Saved OPE comparison figure: {path}")


def plot_is_instability(ope_df: pd.DataFrame) -> None:
    if ope_df.empty or "is_estimate" not in ope_df.columns:
        return

    df = normalize_ope_columns(ope_df)
    df["abs_is_estimate"] = df["is_estimate"].abs()
    df["algorithm_seed"] = df["algorithm"].astype(str) + "_seed_" + df["seed"].astype(str)

    plt.figure(figsize=(10, 5))
    plt.bar(df["algorithm_seed"], df["abs_is_estimate"])
    plt.yscale("log")
    plt.xlabel("Algorithm / seed")
    plt.ylabel("Absolute IS estimate, log scale")
    plt.title("Importance Sampling Instability Across PPO and A2C")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()

    path = f"{FIGURES_DIR}/is_instability_ppo_a2c.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"[INFO] Saved IS instability figure: {path}")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    print("\n[INFO] Building combined PPO/A2C/CQL baseline comparison...\n")

    eval_df = load_ppo_a2c_eval_metrics()
    ope_df = load_ppo_a2c_ope_metrics()
    cql_df = load_cql_eval_metrics()

    combined_df = build_combined_baseline_table(eval_df=eval_df, cql_df=cql_df)

    combined_path = f"{RESULTS_DIR}/combined_rl_baseline_summary.csv"
    save_dataframe(combined_df, combined_path, "combined RL baseline summary")

    if not ope_df.empty:
        ope_combined_path = f"{RESULTS_DIR}/combined_ppo_a2c_ope_metrics.csv"
        save_dataframe(ope_df, ope_combined_path, "combined PPO/A2C OPE metrics")

    print("\n=== Combined RL Baseline Summary ===")
    if not combined_df.empty:
        display_cols = [
            "algorithm",
            "seed",
            "mean_reward",
            "std_reward",
            "mean_episode_length",
            "mean_fluid_bin",
            "mean_vasopressor_bin",
            "action_match_rate",
            "cql_dm_initial_value",
            "observed_dataset_episode_return_mean",
        ]
        display_cols = [c for c in display_cols if c in combined_df.columns]
        print(combined_df[display_cols].to_string(index=False))
    else:
        print("[WARN] Combined baseline summary is empty.")

    if not ope_df.empty:
        ope_norm = normalize_ope_columns(ope_df)
        print("\n=== PPO/A2C OPE Results ===")
        display_cols = [
            "algorithm",
            "seed",
            "true_average_return_from_policy_rollout",
            "is_estimate",
            "wis_estimate",
            "dm_proxy_estimate",
        ]
        display_cols = [c for c in display_cols if c in ope_norm.columns]
        print(ope_norm[display_cols].to_string(index=False))

    plot_ppo_a2c_reward(eval_df)
    plot_vasopressor_comparison(combined_df)
    plot_fluid_comparison(combined_df)
    plot_ope_comparison(ope_df)
    plot_is_instability(ope_df)

    print("\n[DONE] Baseline comparison completed successfully.")
    print(f"Summary table: {combined_path}")
    print(f"Figures directory: {FIGURES_DIR}")


if __name__ == "__main__":
    main()
